# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle



name: Publish
on:
  push:

env:
  sonatypeUsername: ${{ secrets.SONATYPEUSERNAME }}
  sonatypePassword: ${{ secrets.SONATYPEPASSWORD }}
  ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
  ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: CopyAars
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: copyAars
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    
      - name: Publish to GitHub Packages
        run: ./gradlew publish
